# **xG - Goles Espererados - Modelo Machine Learning - Regresión Logística** *PARTE 1*

In [9]:
from statsbombpy import sb
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

In [10]:
import warnings
warnings.filterwarnings("ignore")

In [11]:
df_competiciones = sb.competitions()

In [12]:
df_competiciones.head()

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,9,281,Germany,1. Bundesliga,male,False,False,2023/2024,2024-09-28T20:46:38.893391,2025-07-06T04:26:07.636270,2025-07-06T04:26:07.636270,2024-09-28T20:46:38.893391
1,9,27,Germany,1. Bundesliga,male,False,False,2015/2016,2024-05-19T11:11:14.192381,None,None,2024-05-19T11:11:14.192381
2,1267,107,Africa,African Cup of Nations,male,False,True,2023,2024-09-28T01:57:35.846538,None,None,2024-09-28T01:57:35.846538
3,16,4,Europe,Champions League,male,False,False,2018/2019,2025-05-08T15:10:50.835274,2021-06-13T16:17:31.694,None,2025-05-08T15:10:50.835274
4,16,1,Europe,Champions League,male,False,False,2017/2018,2024-02-13T02:35:28.134882,2021-06-13T16:17:31.694,None,2024-02-13T02:35:28.134882

In [13]:
df_competiciones.shape

(75, 12)

In [14]:
list(df_competiciones.columns)

['competition_id',
 'season_id',
 'country_name',
 'competition_name',
 'competition_gender',
 'competition_youth',
 'competition_international',
 'season_name',
 'match_updated',
 'match_updated_360',
 'match_available_360',
 'match_available']

In [15]:
df_competiciones["competition_name"].value_counts()

competition_name
Champions League           18
La Liga                    18
FIFA World Cup              8
Ligue 1                     3
Copa del Rey                3
FA Women's Super League     3
1. Bundesliga               2
UEFA Women's Euro           2
UEFA Euro                   2
Serie A                     2
Premier League              2
Liga Profesional            2
Women's World Cup           2
Major League Soccer         1
North American League       1
NWSL                        1
African Cup of Nations      1
Indian Super league         1
FIFA U20 World Cup          1
UEFA Europa League          1
Copa America                1
Name: count, dtype: int64

In [16]:
df_competiciones["competition_gender"].value_counts()

competition_gender
male      67
female     8
Name: count, dtype: int64

In [18]:
df_competiciones["season_name"].value_counts()

season_name
2015/2016    6
2023         3
2018/2019    3
2020/2021    2
2008/2009    2
2018         2
2022         2
2019/2020    2
2024         2
2003/2004    2
2004/2005    2
2006/2007    2
2021/2022    2
2009/2010    2
2014/2015    2
2011/2012    2
2017/2018    2
2012/2013    2
2016/2017    2
2010/2011    2
2013/2014    2
2007/2008    1
2005/2006    1
1973/1974    1
1997/1998    1
1981         1
2022/2023    1
1977         1
1986/1987    1
2020         1
1988/1989    1
1958         1
2025         1
2023/2024    1
1962         1
1970         1
1974         1
1986         1
1990         1
1979         1
1977/1978    1
1982/1983    1
1983/1984    1
1970/1971    1
1971/1972    1
1972/1973    1
1999/2000    1
2019         1
Name: count, dtype: int64

In [21]:
df_competiciones_masculino = df_competiciones[df_competiciones["competition_gender"]=="male"].copy()

In [22]:
df_competiciones_masculino.shape

(67, 12)

In [ ]:
df_competiciones_masculino["season_year_texto"] = df_competiciones_masculino["season_name"].astype(str).str[:4]

df_competiciones_masculino["season_year"] = pd.to_numeric(df_competiciones_masculino["season_year_texto"],errors="coerce")

In [ ]:
df_competiciones_masculino[["competition_name", "season_name", "season_year"]].sort_values("season_year", ascending=False)

          competition_name season_name  season_year
21            Copa America        2024         2024
68               UEFA Euro        2024         2024
61     Major League Soccer        2023         2023
0            1. Bundesliga   2023/2024         2023
2   African Cup of Nations        2023         2023
..                     ...         ...          ...
19        Champions League   1971/1972         1971
34          FIFA World Cup        1970         1970
20        Champions League   1970/1971         1970
35          FIFA World Cup        1962         1962
36          FIFA World Cup        1958         1958

[67 rows x 3 columns]

In [28]:
df_competiciones_modelo = df_competiciones_masculino[df_competiciones_masculino["season_year"] >= 2015].copy()

df_competiciones_modelo = df_competiciones_modelo.sort_values(["season_year", "competition_name"],ascending=[False, True])

df_competiciones_modelo

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available,season_year_texto,season_year
21,223,282,South America,Copa America,male,False,True,2024,2024-11-04T16:15:34.886972,None,None,2024-11-04T16:15:34.886972,2024,2024
68,55,282,Europe,UEFA Euro,male,False,True,2024,2024-09-28T16:51:20.698794,2025-03-24T14:12:30.785094,2025-03-24T14:12:30.785094,2024-09-28T16:51:20.698794,2024,2024
0,9,281,Germany,1. Bundesliga,male,False,False,2023/2024,2024-09-28T20:46:38.893391,2025-07-06T04:26:07.636270,2025-07-06T04:26:07.636270,2024-09-28T20:46:38.893391,2023,2023
2,1267,107,Africa,African Cup of Nations,male,False,True,2023,2024-09-28T01:57:35.846538,None,None,2024-09-28T01:57:35.846538,2023,2023
61,44,107,United States of America,Major League Soccer,male,False,False,2023,2025-06-15T12:48:12.599307,2025-07-01T11:17:29.514495,2025-07-01T11:17:29.514495,2025-06-15T12:48:12.599307,2023,2023
29,43,106,International,FIFA World Cup,male,False,True,2022,2024-12-16T10:15:11.055845,2024-12-16T10:21:13.710934,2024-12-16T10:21:13.710934,2024-12-16T10:15:11.055845,2022,2022
58,7,235,France,Ligue 1,male,False,False,2022/2023,2024-12-19T13:56:45.683863,2025-06-30T02:31:32.046070,2025-06-30T02:31:32.046070,2024-12-19T13:56:45.683863,2022,2022
37,1238,108,India,Indian Super league,male,False,False,2021/2022,2024-09-29T17:46:01.175308,None,None,2024-09-29T17:46:01.175308,2021,2021
59,7,108,France,Ligue 1,male,False,False,2021/2022,2025-06-15T12:56:15.594872,2025-06-15T13:02:45.341609,2025-06-15T13:02:45.341609,2025-06-15T12:56:15.594872,2021,2021
38,11,90,Spain,La Liga,male,False,False,2020/2021,2025-01-29T17:39:28.924386,2025-01-29T18:09:18.620699,2025-01-29T18:09:18.620699,2025-01-29T17:39:28.924386,2020,2020
69,55,43,Europe,UEFA Euro,male,False,True,2020,2024-07-31T12:29:15.702309,2024-07-31T12:30:57.587087,2024-07-31T12:30:57.587087,2024-07-31T12:29:15.702309,2020,2020
39,11,42,Spain,La Liga,male,False,False,2019/2020,2024-12-16T16:51:06.833054,2021-06-13T16:17:31.694,None,2024-12-16T16:51:06.833054,2019,2019
3,16,4,Europe,Champions League,male,False,False,2018/2019,2025-05-08T15:10:50.835274,2021-06-13T16:17:31.694,None,2025-05-08T15:10:50.835274,2018,2018
30,43,3,International,FIFA World Cup,male,False,True,2018,2024-06-12T07:38:19.345758,2021-06-13T16:17:31.694,None,2024-06-12T07:38:19.345758,2018,2018
40,11,4,Spain,La Liga,male,False,False,2018/2019,2024-09-22T18:50:23.364757,2021-07-09T14:53:22.103024,None,2024-09-22T18:50:23.364757,2018,2018
4,16,1,Europe,Champions League,male,False,False,2017/2018,2024-02-13T02:35:28.134882,2021-06-13T16:17:31.694,None,2024-02-13T02:35:28.134882,2017,2017
41,11,1,Spain,La Liga,male,False,False,2017/2018,2025-07-14T10:01:16.674864,2021-06-13T16:17:31.694,None,2025-07-14T10:01:16.674864,2017,2017
5,16,2,Europe,Champions League,male,False,False,2016/2017,2024-02-13T02:37:32.205154,2021-06-13T16:17:31.694,None,2024-02-13T02:37:32.205154,2016,2016
42,11,2,Spain,La Liga,male,False,False,2016/2017,2025-03-09T16:03:54.962718,2021-06-13T16:17:31.694,None,2025-03-09T16:03:54.962718,2016,2016
1,9,27,Germany,1. Bundesliga,male,False,False,2015/2016,2024-05-19T11:11:14.192381,None,None,2024-05-19T11:11:14.192381,2015,2015
6,16,27,Europe,Champions League,male,False,False,2015/2016,2024-06-12T07:45:38.786894,2021-06-13T16:17:31.694,None,2024-06-12T07:45:38.786894,2015,2015
43,11,27,Spain,La Liga,male,False,False,2015/2016,2025-04-23T13:59:22.835792,2021-06-13T16:17:31.694,None,2025-04-23T13:59:22.835792,2015,2015
60,7,27,France,Ligue 1,male,False,False,2015/2016,2024-12-16T08:48:23.066123,None,None,2024-12-16T08:48:23.066123,2015,2015
64,2,27,England,Premier League,male,False,False,2015/2016,2025-04-23T14:36:29.347042,2021-06-13T16:17:31.694,None,2025-04-23T14:36:29.347042,2015,2015
66,12,27,Italy,Serie A,male,False,False,2015/2016,2025-07-21T05:01:00.434081,None,None,2025-07-21T05:01:00.434081,2015,2015

### 2) **PARTIDOS**

In [31]:
df_competiciones_modelo = df_competiciones_modelo.reset_index(drop=True)

df_competiciones_modelo.head()

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available,season_year_texto,season_year
0,223,282,South America,Copa America,male,False,True,2024,2024-11-04T16:15:34.886972,None,None,2024-11-04T16:15:34.886972,2024,2024
1,55,282,Europe,UEFA Euro,male,False,True,2024,2024-09-28T16:51:20.698794,2025-03-24T14:12:30.785094,2025-03-24T14:12:30.785094,2024-09-28T16:51:20.698794,2024,2024
2,9,281,Germany,1. Bundesliga,male,False,False,2023/2024,2024-09-28T20:46:38.893391,2025-07-06T04:26:07.636270,2025-07-06T04:26:07.636270,2024-09-28T20:46:38.893391,2023,2023
3,1267,107,Africa,African Cup of Nations,male,False,True,2023,2024-09-28T01:57:35.846538,None,None,2024-09-28T01:57:35.846538,2023,2023
4,44,107,United States of America,Major League Soccer,male,False,False,2023,2025-06-15T12:48:12.599307,2025-07-01T11:17:29.514495,2025-07-01T11:17:29.514495,2025-06-15T12:48:12.599307,2023,2023

In [32]:
lista_partidos = []

for i in range(len(df_competiciones_modelo)):
    
    competition_id = df_competiciones_modelo.loc[i, "competition_id"]
    season_id = df_competiciones_modelo.loc[i, "season_id"]
    competition_name = df_competiciones_modelo.loc[i, "competition_name"]
    season_name = df_competiciones_modelo.loc[i, "season_name"]
    season_year = df_competiciones_modelo.loc[i, "season_year"]
    country_name = df_competiciones_modelo.loc[i, "country_name"]
    
    print("Descargando:", competition_name, "-", season_name)
    
    df_partidos = sb.matches(
        competition_id=competition_id,
        season_id=season_id)
    
    df_partidos["competition_id"] = competition_id
    df_partidos["season_id"] = season_id
    df_partidos["competition_name"] = competition_name
    df_partidos["season_name"] = season_name
    df_partidos["season_year"] = season_year
    df_partidos["country_name"] = country_name
    
    lista_partidos.append(df_partidos)

Descargando: Copa America - 2024
Descargando: UEFA Euro - 2024
Descargando: 1. Bundesliga - 2023/2024
Descargando: African Cup of Nations - 2023
Descargando: Major League Soccer - 2023
Descargando: FIFA World Cup - 2022
Descargando: Ligue 1 - 2022/2023
Descargando: Indian Super league - 2021/2022
Descargando: Ligue 1 - 2021/2022
Descargando: La Liga - 2020/2021
Descargando: UEFA Euro - 2020
Descargando: La Liga - 2019/2020
Descargando: Champions League - 2018/2019
Descargando: FIFA World Cup - 2018
Descargando: La Liga - 2018/2019
Descargando: Champions League - 2017/2018
Descargando: La Liga - 2017/2018
Descargando: Champions League - 2016/2017
Descargando: La Liga - 2016/2017
Descargando: 1. Bundesliga - 2015/2016
Descargando: Champions League - 2015/2016
Descargando: La Liga - 2015/2016
Descargando: Ligue 1 - 2015/2016
Descargando: Premier League - 2015/2016
Descargando: Serie A - 2015/2016

In [33]:
df_partidos_modelo = pd.concat(lista_partidos, ignore_index=True)

df_partidos_modelo.head()

,match_id,match_date,kick_off,home_score,away_score,match_status,match_status_360,last_updated,last_updated_360,match_week,competition_id,competition_country_name,competition_name,competition,season_id,season,home_team_id,home_team,home_team_gender,home_team_group,home_team_country_id,home_team_country_name,away_team_id,away_team,away_team_gender,away_team_group,away_team_country_id,away_team_country_name,competition_stage_id,competition_stage,stadium_id,stadium,stadium_country_id,stadium_country_name,referee_id,referee,referee_country_id,referee_country_name,home_managers,away_managers,home_manager_id,home_manager_name,home_manager_nickname,home_manager_dob,home_manager_country_id,home_manager_country_name,away_manager_id,away_manager_name,away_manager_nickname,away_manager_dob,away_manager_country_id,away_manager_country_name,data_version,shot_fidelity_version,xy_fidelity_version,season_name,season_year,country_name
0,3943077,2024-07-15,04:15:00.000,1,0,available,unscheduled,2024-07-15T15:50:08.671355,None,6,223,South America,Copa America,South America - Copa America,282,2024,779,Argentina,male,None,11,Argentina,769,Colombia,male,None,49,Colombia,26,Final,5337.0,Hard Rock Stadium,241.0,United States of America,2638.0,Raphael Claus,31.0,Brazil,Lionel Sebastián Scaloni,Néstor Gabriel Lorenzo,5677,Lionel Sebastián Scaloni,None,1978-05-16,11,Argentina,5905,Néstor Gabriel Lorenzo,None,1966-02-28,11,Argentina,1.1.0,2,2,2024,2024,South America
1,3943076,2024-07-14,03:00:00.000,2,2,available,unscheduled,2024-07-15T07:57:02.660641,None,6,223,South America,Copa America,South America - Copa America,282,2024,1833,Canada,male,None,40,Canada,783,Uruguay,male,None,242,Uruguay,25,3rd Place Final,52985.0,Bank of America Stadium,241.0,United States of America,1849.0,Alexis Herrera,246.0,Venezuela (Bolivarian Republic),Jesse Marsch,Marcelo Alberto Bielsa Caldera,165,Jesse Marsch,None,1973-11-08,241,United States of America,269,Marcelo Alberto Bielsa Caldera,Marcelo Bielsa,1955-07-21,11,Argentina,1.1.0,2,2,2024,2024,South America
2,3942852,2024-07-11,03:00:00.000,0,1,available,unscheduled,2024-07-15T18:00:33.653673,None,5,223,South America,Copa America,South America - Copa America,282,2024,783,Uruguay,male,None,242,Uruguay,769,Colombia,male,None,49,Colombia,15,Semi-finals,52985.0,Bank of America Stadium,241.0,United States of America,740.0,César Arturo Ramos Palazuelos,147.0,Mexico,Marcelo Alberto Bielsa Caldera,Néstor Gabriel Lorenzo,269,Marcelo Alberto Bielsa Caldera,Marcelo Bielsa,1955-07-21,11,Argentina,5905,Néstor Gabriel Lorenzo,None,1966-02-28,11,Argentina,1.1.0,2,2,2024,2024,South America
3,3942785,2024-07-10,03:00:00.000,2,0,available,unscheduled,2024-07-14T15:55:49.351182,None,5,223,South America,Copa America,South America - Copa America,282,2024,779,Argentina,male,None,11,Argentina,1833,Canada,male,None,40,Canada,15,Semi-finals,1001990.0,MetLife Stadium,241.0,United States of America,1776.0,Piero Maza Gomez,45.0,Chile,Lionel Sebastián Scaloni,Jesse Marsch,5677,Lionel Sebastián Scaloni,None,1978-05-16,11,Argentina,165,Jesse Marsch,None,1973-11-08,241,United States of America,1.1.0,2,2,2024,2024,South America
4,3942416,2024-07-07,01:00:00.000,5,0,available,unscheduled,2024-07-10T06:49:40.099252,None,4,223,South America,Copa America,South America - Copa America,282,2024,769,Colombia,male,None,49,Colombia,798,Panama,male,None,176,Panama,11,Quarter-finals,118193.0,State Farm Stadium,241.0,United States of America,252.0,Maurizio Mariani,112.0,Italy,Néstor Gabriel Lorenzo,Thomas Christiansen Tarín,5905,Néstor Gabriel Lorenzo,None,1966-02-28,11,Argentina,415,Thomas Christiansen Tarín,Thomas Christiansen,1973-03-11,214,Spain,1.1.0,2,2,2024,2024,South America

In [34]:
df_partidos_modelo.shape

(2526, 58)

In [36]:
df_partidos_modelo["competition_name"].value_counts()

competition_name
La Liga                   552
Ligue 1                   435
Premier League            380
Serie A                   380
1. Bundesliga             340
FIFA World Cup            128
Indian Super league       115
UEFA Euro                 102
African Cup of Nations     52
Copa America               32
Major League Soccer         6
Champions League            4
Name: count, dtype: int64

In [44]:
df_partidos_modelo[["competition_name", "season_name", "match_id"]].groupby(["competition_name", "season_name"]).count().sort_values("match_id", ascending=False)

                                    match_id
competition_name       season_name
Serie A                2015/2016         380
Premier League         2015/2016         380
La Liga                2015/2016         380
Ligue 1                2015/2016         377
1. Bundesliga          2015/2016         306
Indian Super league    2021/2022         115
FIFA World Cup         2018               64
                       2022               64
African Cup of Nations 2023               52
UEFA Euro              2020               51
                       2024               51
La Liga                2017/2018          36
                       2020/2021          35
1. Bundesliga          2023/2024          34
La Liga                2018/2019          34
                       2016/2017          34
                       2019/2020          33
Copa America           2024               32
Ligue 1                2022/2023          32
                       2021/2022          26
Major League Soccer    2023                6
Champions League       2018/2019           1
                       2017/2018           1
                       2016/2017           1
                       2015/2016           1

In [45]:
columnas_partidos = ["match_id", "match_date", "competition_name", "season_name", "competition_stage", "home_team", "away_team", "home_score", "away_score"]

df_partidos_modelo[columnas_partidos].head(20)

,match_id,match_date,competition_name,season_name,competition_stage,home_team,away_team,home_score,away_score
0,3943077,2024-07-15,Copa America,2024,Final,Argentina,Colombia,1,0
1,3943076,2024-07-14,Copa America,2024,3rd Place Final,Canada,Uruguay,2,2
2,3942852,2024-07-11,Copa America,2024,Semi-finals,Uruguay,Colombia,0,1
3,3942785,2024-07-10,Copa America,2024,Semi-finals,Argentina,Canada,2,0
4,3942416,2024-07-07,Copa America,2024,Quarter-finals,Colombia,Panama,5,0
5,3942415,2024-07-07,Copa America,2024,Quarter-finals,Uruguay,Brazil,0,0
6,3939986,2024-06-30,Copa America,2024,Group Stage,Argentina,Peru,2,0
7,3939973,2024-06-24,Copa America,2024,Group Stage,Uruguay,Panama,3,1
8,3942229,2024-07-06,Copa America,2024,Quarter-finals,Venezuela,Canada,1,1
9,3942228,2024-07-05,Copa America,2024,Quarter-finals,Argentina,Ecuador,1,1
10,3939985,2024-06-30,Copa America,2024,Group Stage,Canada,Chile,0,0
11,3939984,2024-06-29,Copa America,2024,Group Stage,Colombia,Costa Rica,3,0
12,3939981,2024-06-28,Copa America,2024,Group Stage,Panama,United States,2,1
13,3939992,2024-07-03,Copa America,2024,Group Stage,Costa Rica,Paraguay,2,1
14,3939991,2024-07-03,Copa America,2024,Group Stage,Brazil,Colombia,1,1
15,3939990,2024-07-02,Copa America,2024,Group Stage,United States,Uruguay,0,1
16,3939989,2024-07-02,Copa America,2024,Group Stage,Bolivia,Panama,1,3
17,3939988,2024-07-01,Copa America,2024,Group Stage,Mexico,Ecuador,0,0
18,3939987,2024-07-01,Copa America,2024,Group Stage,Jamaica,Venezuela,0,3
19,3939983,2024-06-29,Copa America,2024,Group Stage,Paraguay,Brazil,1,4

In [46]:
df_partidos_modelo["match_id"].duplicated().sum()

0

In [47]:
df_partidos_modelo["competition_stage"].value_counts()

competition_stage
Regular Season             2203
Group Stage                 228
Round of 16                  40
Quarter-finals               24
Semi-finals                  12
Final                        10
3rd Place Final               4
Play-offs - Semi-Finals       4
Championship - Final          1
Name: count, dtype: int64

In [48]:
df_partidos_modelo["home_team"].value_counts().head(20)

home_team
Barcelona              109
Paris Saint-Germain     51
Bayer Leverkusen        34
Real Madrid             26
Villarreal              24
Sevilla                 24
Real Sociedad           24
Valencia                24
Atlético Madrid         24
Real Betis              24
Eibar                   23
Espanyol                23
Athletic Club           23
Celta Vigo              22
Levante UD              22
Getafe                  22
Granada                 21
Lille                   21
Nantes                  21
Montpellier             21
Name: count, dtype: int64

In [51]:
df_partidos_argentina = df_partidos_modelo[(df_partidos_modelo["home_team"] == "Argentina") | (df_partidos_modelo["away_team"] == "Argentina")].copy()

df_partidos_argentina[columnas_partidos].sort_values("match_date")

,match_id,match_date,competition_name,season_name,competition_stage,home_team,away_team,home_score,away_score
573,7531,2018-06-16,FIFA World Cup,2018,Group Stage,Argentina,Iceland,1,1
569,7545,2018-06-21,FIFA World Cup,2018,Group Stage,Argentina,Croatia,0,3
579,7564,2018-06-26,FIFA World Cup,2018,Group Stage,Nigeria,Argentina,1,2
553,7580,2018-06-30,FIFA World Cup,2018,Round of 16,France,Argentina,4,3
212,3857300,2022-11-22,FIFA World Cup,2022,Group Stage,Argentina,Saudi Arabia,1,2
188,3857289,2022-11-26,FIFA World Cup,2022,Group Stage,Argentina,Mexico,2,0
186,3857264,2022-11-30,FIFA World Cup,2022,Group Stage,Poland,Argentina,0,2
176,3869151,2022-12-03,FIFA World Cup,2022,Round of 16,Argentina,Australia,2,1
181,3869321,2022-12-09,FIFA World Cup,2022,Quarter-finals,Netherlands,Argentina,2,2
194,3869519,2022-12-13,FIFA World Cup,2022,Semi-finals,Argentina,Croatia,3,0
184,3869685,2022-12-18,FIFA World Cup,2022,Final,Argentina,France,3,3
31,3939969,2024-06-21,Copa America,2024,Group Stage,Argentina,Canada,2,0
24,3939977,2024-06-26,Copa America,2024,Group Stage,Chile,Argentina,0,1
6,3939986,2024-06-30,Copa America,2024,Group Stage,Argentina,Peru,2,0
9,3942228,2024-07-05,Copa America,2024,Quarter-finals,Argentina,Ecuador,1,1
3,3942785,2024-07-10,Copa America,2024,Semi-finals,Argentina,Canada,2,0
0,3943077,2024-07-15,Copa America,2024,Final,Argentina,Colombia,1,0

In [54]:
df_partidos_modelo.to_csv("../data/processed/df_partidos_modelo.csv", index=False)